name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Set image tag
      run: echo "IMAGE_TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

    - name: Build and push Docker image
      run: |
        docker build -t vikas277/stu-3:${{ env.IMAGE_TAG }} .
        docker push vikas277/stu-3:${{ env.IMAGE_TAG }}

    - name: Generate Dockerrun.aws.json
      run: |
        echo '{
          "AWSEBDockerrunVersion": "1",
          "Image": {
            "Name": "vikas277/stu-3:${{ env.IMAGE_TAG }}",
            "Update": "true"
          },
          "Ports": [
            {
              "ContainerPort": 8000,
              "HostPort": 80
            }
          ],
          "Logging": "/var/log/nginx"
        }' > Dockerrun.aws.json

    - name: Upload Dockerrun.aws.json as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: Dockerrun
        path: Dockerrun.aws.json

    - name: Deploy to AWS Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ${{ secrets.EB_APPLICATION_NAME }}
        environment_name: ${{ secrets.EB_ENVIRONMENT_NAME }}
        version_label: "${{ env.IMAGE_TAG }}"
        region: ${{ secrets.AWS_REGION }}
        deployment_package: Dockerrun.aws.json
